title: Fabienne Krotoff Ostéopathe D.O.
description: Cabinet d'ostéopathie de Fabienne Krotoff 75015 Paris - 01 45 31 98 48
lang: fr
author: Fabienne Krotoff
address: 8 rue Desnouettes Paris 15
tel: 01 45 31 98 48
email: krotoffosteo@gmail.com

twitter_username: Osteo15
facebook_username: Osteo15
googleplus_username: 104301362970770277035
linkedin_username: fabiennekrotoff

url: "https://osteo15.com"
permalink: pretty

markdown: kramdown
#kramdown:
#  input: GFM # Github Flavored Markdown

exclude: [
  "vendor",
  "README.md",
  "blogger-redirections.md",
  "s3_website.yml",
  ".env*",
  "Gemfile",
  "Gemfile.lock",
  "Rakefile"
]

gems:
  - jekyll-sitemap
  - octopress-minify-html

minify_html: false
